source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NextGrowingTextView_Example', :exclusive => true do
  pod "NextGrowingTextView", :path => "../"
end

target 'NextGrowingTextView_Tests', :exclusive => true do
  pod "NextGrowingTextView", :path => "../"

  
end
