name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.2"
      - uses: actions/checkout@v2
      # - run: set -o pipefail && xcodebuild build -project NextGrowingTextView.xcodeproj -scheme NextGrowingTextView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
      - run: pod lib lint --allow-warnings
